service: serverless-bun-app
frameworkVersion: '3'

provider:
  name: aws
  architecture: arm64
    	
  ecr:
    images:
      bun-image:
        path: ../
functions:
  hello:
    image:
      name: bun-image
    url: true
